name: Clean docker
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 0 */2 * *"

jobs:
  build:
    runs-on: [self-hosted, new]
    steps:
      - name: clean docker
        run: |
          sudo docker system prune -f
